#!/bin/bash
set -e

if [ -x /usr/bin/update-desktop-database ]; then
    update-desktop-database /usr/share/applications > /dev/null 2>&1 || true
fi

if [ -x /usr/bin/update-icon-caches ]; then
    update-icon-caches /usr/share/icons/* > /dev/null 2>&1 || true
fi

exit 0
